import { ReactElement } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import DragComponent from "@/components/DragComponent";
import SideMenu from "@/components/SideMenu";
import { PanelContents } from "@/components/PanelContents";
import { Grid, Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home(): ReactElement {
  const fruits = [
    {
      id: 1,
      name: "apple",
      price: 100,
      area: "Aomori",
    },
    {
      id: 2,
      name: "banana",
      price: 200,
      area: "Okinawa",
    },
    {
      id: 3,
      name: "orange",
      price: 300,
      area: "Wakayama",
    },
    {
      id: 4,
      name: "Strawberry",
      price: 300,
      area: "Shizuoka",
    },
  ];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box display={"flex"}>
        <SideMenu />
        <Box flexGrow={1}>
          <DragComponent />
          <Grid container spacing={2}>
            {fruits.map((value) => (
              <PanelContents key={value.id} value={value} />
            ))}
          </Grid>
        </Box>
      </Box>
    </div>
  );
}
